### ISSUE TITLE
No CA Certificate to connect with

### ISSUE THREAD

**Issue by awalGarg** [azure-openvpn/azure-openvpn.github.io#4]
Hi there,

Thanks for the guide. I have set up an OpenVPN server as described, have a username and password. But when trying to connect to it from the client (Ubuntu 14.04 LTS), it asks for a CA Certificate file. Without it, it won't allow me to connect. How can I generate that file?

Thanks, <3

**Comment by lilianmoraru** [comment]
When I did this I was using the OpenVPN client I reference at the end.
When you try to connect with it, it asks if you want to install the certificate, or something like this.

Anyway, here is the first result from Google for query "openvpn install ca certificate": https://openvpn.net/index.php/access-server/docs/admin-guides/175-how-to-replace-the-access-server-private-key-and-certificate.html .

**Comment by awalGarg** [comment]
Hey @lilianmoraru sorry for the late reply.

The standard CLI based OpenVPN client doesn't ask you for anything, it just expects you to pass stuff along.

The link you gave is for the OpenVPN Web admin area's SSL certificates which is not quite what I was looking for.

However I found that by going to `https://<your-vpn-address>:<vpnport>/` (see no `/admin` path), and logging in to the `openvpn` account, you will get an option to download a userlocked `.ovpn` profile which contains the details, certificates and everything. Then you can execute this command:

```sh
sudo openvpn --config <path/to/.ovpn>
```
the `sudo` part is important. It will connect with that `.ovpn` file and ask for a username and password.

If you don't wanna type your username/password everytime, you can do the following: put them in a new file in the following format:
```
<username>
<password>
```

(without the `<` and `>` ofcourse). No trailing slashes or extra newlines, no quotes. just the username and password separated by a newline, in that order. Then save it as `credentials.conf` and do the following:

```sh
sudo openvpn --config <path/to/.ovpn> --auth-user-pass <path/to/credentials.conf>
```

and it won't ask for the password. If you don't wanna save your password in plaintext like me, you can setup a quick python script that allows you to enter/update/remove the credentials in a file in encrypted format, and also allows you to connect to the vpn and disconnect as a service without having to dedicate a shell. It was quite easy to do for me.

Hope that helps future readers!
